const { lambdaAction } = require('./lambda/lambda.action');

require('sade')('lambda [name]', true)
    .version('1.0.0')
    .describe('Create a lambda function')
    .option('--method, -m', 'Api Gateweay Method')
    .option('--typescript, -t', 'Enable Typescript Support')
    .option('--schema, -s', 'Use Module Schema')
    .option('--auth, -a', 'Use Token Authorizer')
    .example('yarn lambda')
    .example('yarn lambda createUser')
    .example('yarn lambda updateUser -m put')
    .example('yarn lambda createUser -m post')
    .example('yarn lambda -m get')
    .example('yarn lambda -t')
    .example('yarn lambda getFunUser -t')
    .example('yarn lambda getMyUser -tm get')
    .example('yarn lambda listUser -s')
    .example('yarn lambda listActiveUser -tsm get')
    .example('yarn lambda connectSocket -m websocket')
    .example('yarn lambda deleteUser -a')
    .example('yarn lambda listUser -tsam get')
    .action(lambdaAction)
    .parse(process.argv);